version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=nakama
      - POSTGRES_PASSWORD=localdb
      - POSTGRES_USER=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d nakama"]
      interval: 5s
      timeout: 5s
      retries: 5

  nakama:
    container_name: nakama
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=localdb
      - DB_NAME=nakama
      - PORT=7350
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "7349:7349"
      - "7350:7350"
      - "7351:7351"

volumes:
  pgdata:
